name: Test Alembic Migrations

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-alembic:
    runs-on: ubuntu-latest
    steps:
      - name: Install SQL Server
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine
          sa-password: Wh4t3V3r! # The password can be shown here as the runner will be deleted
          version: 2019
          collation: SQL_Latin1_General_CP1_CI_AS

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install alembic

      - name: Run Alembic migrations
        run: alembic upgrade head
